<?php

// debug mode. Set to true to get debug messages on screen.
$debug = false;

// database and debug functionality
include('utils.php');

session_start();

$time = date("H:i:s");

$file_use_key = $_GET["fileuseid"];
debug_msg("Looking for file use (No. ".$file_use_key.")");

// select database  
open_db();

// Check if file_use (generated by javascript) is in the DB.
// If file_use has been recorded, select corresponding session
$sql = "SELECT session_id FROM file_uses_tbl WHERE file_use_key='$file_use_key'";

// Get session_key. If file_use has not been recorded before, session_key is not found here
if (!($session_key = query_one_item($sql)))
{
   // In that case, get session key through php session management
   debug_msg("File use not yet recorded.");
   $session_key = session_id();

   // If file_use is not in the DB, session_id may not be either.
   // Is there a session in the DB with this key?
   debug_msg("Looking for session (No. ".$session_key.")");
   $sql = "SELECT count(*) FROM sessions_tbl WHERE session_key='$session_key'";

   // If not, record it now
   $session_not_recorded = (query_one_item($sql)==0);
   if ($session_not_recorded)
   {
	  debug_msg("Session not yet recorded. Recording now.");
      $client_ip = $_SERVER['REMOTE_ADDR'];
      $remote_host = $_SERVER['REMOTE_HOST'];
	  $client_desc = $_SERVER['HTTP_USER_AGENT'];

 	  $date = date("Y-m-d");

      $sql = "INSERT INTO";
      $sql .= " sessions_tbl (client_description, client_ip, client_host_name, session_date, session_time, session_key)";
      $sql .= " VALUES ('$client_desc','$client_ip','$remote_host','$date','$time','$session_key')";

	  query_db($sql);

   } // finish recording the new session

   // Now record the file_use for this session

   debug_msg("Recording the file use.");

   $sql = "INSERT INTO";
   $sql .= " file_uses_tbl (file_id, file_use_key, session_id, file_use_edit, file_use_time)";
   $sql .= " VALUES (0,'$file_use_key','$session_key','off','$time')";

   query_db($sql);

} // finish recording the file_use

// record the command
$command = $_GET["command"];

debug_msg("Recording the user command: ".$command);

$sql = "INSERT INTO";
$sql .= " commands_given_tbl (command, file_use_id, command_time)";
$sql .= " VALUES ('$command','$file_use_key','$time')";

query_db($sql);

mysql_close(); // on ferme la connexion

?>
